In [1]:
import numpy as np

In [2]:
x = np.array([0,1,2])

print(x)
print(x.shape)

[0 1 2]
(3,)


In [3]:
x = np.array([[0],[1],[2]])

print(x)
print(x.shape)

[[0]
 [1]
 [2]]
(3, 1)


In [4]:
x = np.array([[[0],[1],[2]]])
print(x)
print(x.shape)

[[[0]
  [1]
  [2]]]
(1, 3, 1)


In [5]:
np.squeeze(x).shape

(3,)

In [6]:
#Unsqueeze

import torch

In [7]:
a = torch.tensor([1,2,3,4])
print(a)
print(a.shape)

tensor([1, 2, 3, 4])
torch.Size([4])


In [8]:
print(torch.unsqueeze(a,1))
print(torch.unsqueeze(a,1).shape)

tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])
